export { default as Header } from "./header";
export { default as Footer } from "./footer";
export { default as FormQueixante } from "./formQueixante";
export { default as FormLogin } from "./queixanteLogin";
export { default as Sidebar } from "./sidebar";
export { default as CardNavigator } from "./cardNavigator";
export { default as Navigator } from "./navigatorHome";
export { default as ContainerDashboard } from "./containerDashboard";
export { default as Tabs } from "./tabs";
export { default as AddressForm } from "./addressForm";
export { default as ProfileForm } from "./profileForm";
export { default as QueixaForm } from "./queixaForm";
export { default as FormGoverno } from "./formGoverno";
export { default as GovernoLogin } from "./governoLogin"
export { default as CadpcdForm } from "./cadpcdForm"
export { default as Grafico } from "./dashboard"
export { default as BarChart } from "./barChart"
export { default as LineChart } from "./lineChart"
